Repository silwalanish/minecraft2d, pull requests merged in 2019-10, with the labels that each got.

#2 Add screenshot of games in README
  README.md
  screenshots/creative_mode.png
  screenshots/gameover.png
  screenshots/gameplay.png
  screenshots/logo.png
  screenshots/mainmenu.png
  screenshots/map_selector.png
Labels: documentation, screenshot

#6 Refactor game_scenes.js into separate files for each scene.
  index.html
  js/game_scenes.js
  js/game_scenes/choose_map_scene.js
  js/game_scenes/creative_game_scene.js
  js/game_scenes/game_end_scene.js
  js/game_scenes/game_scene.js
  js/game_scenes/main_menu_scene.js
  js/game_scenes/normal_game_scene.js
Labels: enhancement, refactor

#10 Refactor game_scenes.js into separate files for each scene.
  index.html
  js/game_scenes.js
  js/game_scenes/choose_map_scene.js
  js/game_scenes/creative_game_scene.js
  js/game_scenes/game_end_scene.js
  js/game_scenes/game_scene.js
  js/game_scenes/main_menu_scene.js
  js/game_scenes/normal_game_scene.js
Labels: enhancement, refactor

#12 Add public copyright license
  LICENSE
  css/reset.css
  js/core/assets.js
  js/core/camera.js
  js/core/collider.js
  js/core/controller.js
  js/core/display.js
  js/core/game.js
  js/core/scene.js
  js/core/sprites.js
  js/core/ui.js
  js/core/vector.js
  js/foods.js
  js/game_maps.js
  js/game_scenes/choose_map_scene.js
  js/game_scenes/creative_game_scene.js
  js/game_scenes/game_end_scene.js
  js/game_scenes/game_scene.js
  js/game_scenes/main_menu_scene.js
  js/game_scenes/normal_game_scene.js
  js/grid.js
  js/grounds.js
  js/height_map.js
  js/scripts.js
  js/steve.js
  js/utils.js
  js/zombie.js
  package.json
  yarn.lock
Labels: license

#15 Added a credits scene
  index.html
  js/game_scenes/credits_scene.js
  js/game_scenes/main_menu_scene.js
Labels: enhancement

#17 Readme assets preview
  README.md
Labels: documentation

#18 Add Help scene
  index.html
  js/game_scenes/help_scene.js
  js/game_scenes/main_menu_scene.js
Labels: enhancement
